data:
	wget http://www.jarrodmillman.com/rcsds/_downloads/actc.txt
	wget http://nipy.bic.berkeley.edu/rcsds/mni_icbm152_nlin_asym_09c_2mm/mni_icbm152_csf_tal_nlin_asym_09c_2mm.nii
	wget http://openfmri.s3.amazonaws.com/tarballs/ds115_sub010-014.tgz

validate:
	python data.py
